# Generated by Django 4.0.4 on 2022-04-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.CharField(max_length=50)),
                ('startTime', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('typeClass', models.CharField(max_length=50)),
                ('classUC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classuc')),
            ],
        ),
        migrations.AddField(
            model_name='classuc',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uc'),
        ),
        migrations.CreateModel(
            name='StudentUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uc')),
            ],
            options={
                'unique_together': {('student', 'uc')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed1', models.BooleanField()),
                ('confirmed2', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
                ('class1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class2', to='app.class')),
                ('st1ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='request1', to='app.student')),
                ('st2ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='request2', to='app.student')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uc')),
            ],
            options={
                'unique_together': {('st1ID', 'st2ID')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classuc',
            unique_together={('uc', 'cl')},
        ),
    ]
