# Generated by Django 4.0.4 on 2022-04-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='class2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class2', to='app.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='class1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='class1', to='app.class'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
