# Generated by Django 4.0.4 on 2022-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_class2_alter_class_code_alter_class_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='request',
            name='token1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='token2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='confirmed1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='confirmed2',
            field=models.BooleanField(default=False),
        ),
    ]
