# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlerequest',
            old_name='st1ID',
            new_name='st',
        ),
    ]
