# Generated by Django 4.0.4 on 2022-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_request_unique_together_request_token1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuc',
            name='cl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
            preserve_default=False,
        ),
    ]
