# Generated by Django 4.0.4 on 2022-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_st1id_singlerequest_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlerequest',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
