# Generated by Django 4.0.4 on 2022-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_singlerequest_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
