# Generated by Django 4.0.4 on 2022-05-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentuc_cl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentuc',
            unique_together={('student', 'uc', 'cl')},
        ),
    ]
