# Generated by Django 4.0.4 on 2022-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_studentuc_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='classNoUnique',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uc',
            name='initials',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='uc',
            name='code',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('code',), name='classCodeUnique'),
        ),
    ]
